[[Ccluster]]
arch = "aarch64"
git-tree-sha1 = "2f99c2222f8b1e91a99a8cdbefa646654bb59446"
libc = "glibc"
os = "linux"

    [[Ccluster.download]]
    sha256 = "f1b4e022e3794be4de71f0060e4dc848701b943b078c43eed47a9bff3f60ca45"
    url = "https://github.com/JuliaBinaryWrappers/Ccluster_jll.jl/releases/download/Ccluster-v1.1.6+0/Ccluster.v1.1.6.aarch64-linux-gnu.tar.gz"
[[Ccluster]]
arch = "aarch64"
git-tree-sha1 = "09f921690c6413e8f71f27d4c8216e10b47482f0"
libc = "musl"
os = "linux"

    [[Ccluster.download]]
    sha256 = "9b4140491ebdf1759861e30323c081aa1869903f660428df31b7afc540bdcd22"
    url = "https://github.com/JuliaBinaryWrappers/Ccluster_jll.jl/releases/download/Ccluster-v1.1.6+0/Ccluster.v1.1.6.aarch64-linux-musl.tar.gz"
[[Ccluster]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b1f4746c81018c911acce8822f792e3a904a048a"
libc = "glibc"
os = "linux"

    [[Ccluster.download]]
    sha256 = "107b3b8555039d9daa188a757263350bd11e5cdda5aeeee0fdc3ff31d52806a0"
    url = "https://github.com/JuliaBinaryWrappers/Ccluster_jll.jl/releases/download/Ccluster-v1.1.6+0/Ccluster.v1.1.6.armv7l-linux-gnueabihf.tar.gz"
[[Ccluster]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b3bb27ebacd82f85407b2ac04cca345768051ee4"
libc = "musl"
os = "linux"

    [[Ccluster.download]]
    sha256 = "860bd494aa2ab7344a416e919afd272cca054d978f9107edff51af8522cdecb3"
    url = "https://github.com/JuliaBinaryWrappers/Ccluster_jll.jl/releases/download/Ccluster-v1.1.6+0/Ccluster.v1.1.6.armv7l-linux-musleabihf.tar.gz"
[[Ccluster]]
arch = "i686"
git-tree-sha1 = "7e24b788e9d9ebbf5b264a325085f1bfb721cbbc"
libc = "glibc"
os = "linux"

    [[Ccluster.download]]
    sha256 = "4a6d6a1d204b3a95da113595df0451d580a98e594be5ba29e8073bfa69684473"
    url = "https://github.com/JuliaBinaryWrappers/Ccluster_jll.jl/releases/download/Ccluster-v1.1.6+0/Ccluster.v1.1.6.i686-linux-gnu.tar.gz"
[[Ccluster]]
arch = "i686"
git-tree-sha1 = "1012157b4e6c2f607660f996e69ed3a62082d83f"
libc = "musl"
os = "linux"

    [[Ccluster.download]]
    sha256 = "33bb17a2675163b91495311f13610190bd94f9fb1ced8e3142bcfe19bad0f325"
    url = "https://github.com/JuliaBinaryWrappers/Ccluster_jll.jl/releases/download/Ccluster-v1.1.6+0/Ccluster.v1.1.6.i686-linux-musl.tar.gz"
[[Ccluster]]
arch = "i686"
git-tree-sha1 = "b2cfedc55838cb58a32138b5153b89fcb82409f1"
os = "windows"

    [[Ccluster.download]]
    sha256 = "77f03a2b1ca7dc414f7b6712ea258705e50c8d4bf03a095e5cf68ca74e545ead"
    url = "https://github.com/JuliaBinaryWrappers/Ccluster_jll.jl/releases/download/Ccluster-v1.1.6+0/Ccluster.v1.1.6.i686-w64-mingw32.tar.gz"
[[Ccluster]]
arch = "powerpc64le"
git-tree-sha1 = "13c7811f111c61ca7a3de0a8075af902e3d868f3"
libc = "glibc"
os = "linux"

    [[Ccluster.download]]
    sha256 = "6bc5ffce4a881a0a66237526845033260d9552444b92557e7c6a357876c11d40"
    url = "https://github.com/JuliaBinaryWrappers/Ccluster_jll.jl/releases/download/Ccluster-v1.1.6+0/Ccluster.v1.1.6.powerpc64le-linux-gnu.tar.gz"
[[Ccluster]]
arch = "x86_64"
git-tree-sha1 = "bb9cad7d063ebfe06b02b3d40057a3cae2924144"
os = "macos"

    [[Ccluster.download]]
    sha256 = "e415fdcbb38d0d1840ae4d379c06446cca378e14138838aaad64224e499edcf9"
    url = "https://github.com/JuliaBinaryWrappers/Ccluster_jll.jl/releases/download/Ccluster-v1.1.6+0/Ccluster.v1.1.6.x86_64-apple-darwin.tar.gz"
[[Ccluster]]
arch = "x86_64"
git-tree-sha1 = "7524922475b968e0b4750f25dfc030c1fc43d65e"
libc = "glibc"
os = "linux"

    [[Ccluster.download]]
    sha256 = "7e107dbd8c0c496046caed96ca4334423c2e6a74a4b6b157ed5af403fa9e113f"
    url = "https://github.com/JuliaBinaryWrappers/Ccluster_jll.jl/releases/download/Ccluster-v1.1.6+0/Ccluster.v1.1.6.x86_64-linux-gnu.tar.gz"
[[Ccluster]]
arch = "x86_64"
git-tree-sha1 = "0f2ea87b05aef2acfaf2da90158e149268f98207"
libc = "musl"
os = "linux"

    [[Ccluster.download]]
    sha256 = "03d7b3e37a2dfc33b9de960d8ff3b30295a08ed754c63d8be622b0cbad80c657"
    url = "https://github.com/JuliaBinaryWrappers/Ccluster_jll.jl/releases/download/Ccluster-v1.1.6+0/Ccluster.v1.1.6.x86_64-linux-musl.tar.gz"
[[Ccluster]]
arch = "x86_64"
git-tree-sha1 = "a186e291c3e41b2a81dab141d74456feb4b98789"
os = "freebsd"

    [[Ccluster.download]]
    sha256 = "60613ae0a594f8c7aa65f8ba8a93f7418b293d11984b6c015e7ea9d763187665"
    url = "https://github.com/JuliaBinaryWrappers/Ccluster_jll.jl/releases/download/Ccluster-v1.1.6+0/Ccluster.v1.1.6.x86_64-unknown-freebsd.tar.gz"
[[Ccluster]]
arch = "x86_64"
git-tree-sha1 = "80647ff9b464acc7bc2f01e39e51834e5c1af252"
os = "windows"

    [[Ccluster.download]]
    sha256 = "7190a867cb3af24ccc9185be3ed7c40c908342c382f09b56d7ede1e87557164a"
    url = "https://github.com/JuliaBinaryWrappers/Ccluster_jll.jl/releases/download/Ccluster-v1.1.6+0/Ccluster.v1.1.6.x86_64-w64-mingw32.tar.gz"
